version: '3.8'

networks:
  app-network:
    external: true
    name: personal-chat-project_app-network

services:
  ui:
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../..:/workspaces:cached
      - node_modules:/workspaces/ui/node_modules
    working_dir: /workspaces/ui
    command: sleep infinity
    networks:
      - app-network
    ports:
      - "3010:3000"
    environment:
      - NODE_ENV=development
      # - AI_BACKEND=http://ai:8010
      # - MONGODB_URI=mongodb://db:27020/personal-chat

volumes:
  node_modules: 